# Generated by Django 5.1.3 on 2024-11-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('copy', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('tags', models.TextField()),
                ('address', models.TextField()),
                ('desc', models.TextField()),
                ('youtube_url', models.TextField()),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('panorama_img', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('title_content', models.CharField(max_length=255)),
                ('desc_content', models.TextField()),
                ('price', models.TextField()),
                ('apartment_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
