# Generated by Django 5.1.3 on 2024-11-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
