# Generated by Django 5.1.3 on 2024-11-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(default='Unknown City', max_length=255),
            preserve_default=False,
        ),
    ]
